Repository AdultOfNineteen/WINEY-Server, pull requests merged in 2023-08, with the labels that each got.

#13 WIN-56 : 회원탈퇴
  Winey-API/src/main/java/com/example/wineyapi/common/annotation/CheckIdExistence.java
  Winey-API/src/main/java/com/example/wineyapi/common/aop/CheckIdExistenceAspect.java
  Winey-API/src/main/java/com/example/wineyapi/config/SecurityConfig.java
  Winey-API/src/main/java/com/example/wineyapi/user/controller/UserController.java
  Winey-API/src/main/java/com/example/wineyapi/user/converter/UserConverter.java
  Winey-API/src/main/java/com/example/wineyapi/user/dto/UserResponse.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserService.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-API/src/main/resources/application.yml
  Winey-Common/src/main/java/com/example/wineycommon/exception/ExceptionAdvice.java
Labels: 🚀Feature

#14 WIN-57 : 문자 인증
  Winey-API/build.gradle
  Winey-API/src/main/java/com/example/wineyapi/user/controller/UserController.java
  Winey-API/src/main/java/com/example/wineyapi/user/converter/UserConverter.java
  Winey-API/src/main/java/com/example/wineyapi/user/dto/UserRequest.java
  Winey-API/src/main/java/com/example/wineyapi/user/dto/UserResponse.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserService.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/ExceptionAdvice.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/MessageException.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/UserException.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/errorcode/CommonResponseStatus.java
  Winey-Common/src/main/java/com/example/wineycommon/properties/CoolSmsProperties.java
  Winey-Common/src/main/resources/application-common.yml
  Winey-Domain/src/main/java/com/example/wineydomain/common/model/VerifyMessageStatus.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/SocialType.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/repository/UserRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/verificationMessage/entity/VerificationMessage.java
  Winey-Domain/src/main/java/com/example/wineydomain/verificationMessage/repository/VerificationMessageRepository.java
Labels: documentation, 🚀Feature

#18 WIN-57: 스웨거 스키마 구체화
  Winey-API/src/main/resources/application.yml
Labels: documentation

#17 Win 72
  Winey-API/src/main/java/com/example/wineyapi/wine/controller/WineController.java
  Winey-API/src/main/java/com/example/wineyapi/wine/convertor/WineConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/wine/dto/WineResponse.java
  Winey-API/src/main/java/com/example/wineyapi/wine/service/WineHelper.java
  Winey-API/src/main/java/com/example/wineyapi/wine/service/WineService.java
  Winey-API/src/main/java/com/example/wineyapi/wine/service/WineServiceImpl.java
  Winey-API/src/main/resources/application.yml
  Winey-Common/src/main/java/com/example/wineycommon/annotation/Helper.java
  Winey-Domain/build.gradle
  Winey-Domain/src/main/java/com/example/wineydomain/config/QueryDslConfig.java
  Winey-Domain/src/main/java/com/example/wineydomain/preference/entity/Preference.java
  Winey-Domain/src/main/java/com/example/wineydomain/preference/repository/PreferenceRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/tastingNote/repository/TastingNoteCustomRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/tastingNote/repository/TastingNoteRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/tastingNote/repository/TastingNoteRepositoryImpl.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/User.java
  Winey-Domain/src/main/java/com/example/wineydomain/wine/entity/Wine.java
  Winey-Domain/src/main/java/com/example/wineydomain/wine/entity/WineType.java
  Winey-Domain/src/main/java/com/example/wineydomain/wine/repository/WineRepository.java
  Winey-Domain/src/main/resources/application-domain-dev.yml
  Winey-Domain/src/main/resources/application-domain-local.yml
  build.gradle
Labels: 🚀Feature, 🔨Refactor
