Repository AdultOfNineteen/WINEY-Server, pull requests merged in 2023-10, with the labels that each got.

#32 refactor: 구글로그인 accessToken을 idToken으로 변경
  Winey-Domain/src/main/generated/com/example/wineydomain/badge/entity/QUserWineBadge.java
  Winey-Domain/src/main/generated/com/example/wineydomain/badge/entity/QWineBadge.java
  Winey-Domain/src/main/generated/com/example/wineydomain/common/model/QBaseEntity.java
  Winey-Domain/src/main/generated/com/example/wineydomain/image/entity/QImage.java
  Winey-Domain/src/main/generated/com/example/wineydomain/image/entity/QTastingNoteImage.java
  Winey-Domain/src/main/generated/com/example/wineydomain/image/entity/QWineBadgeImage.java
  Winey-Domain/src/main/generated/com/example/wineydomain/image/entity/QWineImage.java
  Winey-Domain/src/main/generated/com/example/wineydomain/preference/entity/QPreference.java
  Winey-Domain/src/main/generated/com/example/wineydomain/tastingNote/entity/QPairing.java
  Winey-Domain/src/main/generated/com/example/wineydomain/tastingNote/entity/QSmellKeywordTastingNote.java
  Winey-Domain/src/main/generated/com/example/wineydomain/tastingNote/entity/QTastingNote.java
  Winey-Domain/src/main/generated/com/example/wineydomain/user/entity/QAuthority.java
  Winey-Domain/src/main/generated/com/example/wineydomain/user/entity/QUser.java
  Winey-Domain/src/main/generated/com/example/wineydomain/verificationMessage/entity/QVerificationMessage.java
  Winey-Domain/src/main/generated/com/example/wineydomain/wine/entity/QRecommendWine.java
  Winey-Domain/src/main/generated/com/example/wineydomain/wine/entity/QRecommendWinePk.java
  Winey-Domain/src/main/generated/com/example/wineydomain/wine/entity/QWine.java
  Winey-Domain/src/main/generated/com/example/wineydomain/wineTip/entity/QWineTip.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/google/client/GoogleOauth2Client.java
Labels: 🔨Refactor

#35 refactor: 중복 가입 에러 문구 수정 타입만 내려주는 방식
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
Labels: 🔨Refactor

#38 WIN-116 : 애플로그인 구현
  .github/workflows/dev_api_ci_cd.yml
  Winey-API/src/main/java/com/example/wineyapi/user/converter/UserConverter.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-API/src/main/resources/application.yml
  Winey-Common/src/main/java/com/example/wineycommon/exception/errorcode/CommonResponseStatus.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/client/AppleOauth2Client.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/dto/AppleMember.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/dto/ApplePublicKey.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/dto/ApplePublicKeys.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/util/AppleClaimsValidator.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/util/AppleJwtParser.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/util/AppleOAuthUserProvider.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/util/EncryptUtils.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/oauth/apple/util/PublicKeyGenerator.java
  Winey-Infrastructure/src/main/resources/application-infrastructure.yml
Labels: 🚀Feature

#26 WIN-93 : 와인 상세 조회
  Winey-API/src/main/java/com/example/wineyapi/wine/controller/WineController.java
  Winey-API/src/main/java/com/example/wineyapi/wine/convertor/WineConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/wine/dto/WineResponse.java
  Winey-API/src/main/java/com/example/wineyapi/wine/service/WineService.java
  Winey-API/src/main/java/com/example/wineyapi/wine/service/WineServiceImpl.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/errorcode/CommonResponseStatus.java
  Winey-Domain/src/main/java/com/example/wineydomain/tastingNote/repository/TastingNoteCustomRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/tastingNote/repository/TastingNoteRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/wine/entity/WineSummary.java
  Winey-Domain/src/main/java/com/example/wineydomain/wine/exception/ReadWineErrorCode.java
Labels: 🚀Feature

#39 WIN-126 : 회원탈퇴 기능 재개발
  .github/workflows/dev_api_ci_cd.yml
  Winey-API/src/main/java/com/example/wineyapi/common/AuthorityGenerator.java
  Winey-API/src/main/java/com/example/wineyapi/common/TestController.java
  Winey-API/src/main/java/com/example/wineyapi/common/annotation/CheckOwnAccount.java
  Winey-API/src/main/java/com/example/wineyapi/common/aop/CheckOwnAccountAspect.java
  Winey-API/src/main/java/com/example/wineyapi/config/SecurityConfig.java
  Winey-API/src/main/java/com/example/wineyapi/config/SwaggerConfig.java
  Winey-API/src/main/java/com/example/wineyapi/security/JwtService.java
  Winey-API/src/main/java/com/example/wineyapi/tastingNote/controller/TastingNoteController.java
  Winey-API/src/main/java/com/example/wineyapi/tastingNote/convertor/TastingNoteConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/tastingNote/service/TastingNoteService.java
  Winey-API/src/main/java/com/example/wineyapi/tastingNote/service/TastingNoteServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/user/controller/UserController.java
  Winey-API/src/main/java/com/example/wineyapi/user/converter/UserConverter.java
  Winey-API/src/main/java/com/example/wineyapi/user/dto/UserResponse.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserService.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/convertor/WineBadgeConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeService.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeServiceImpl.java
  Winey-Common/build.gradle
  Winey-Common/src/main/java/com/example/wineycommon/annotation/RedissonLock.java
  Winey-Common/src/main/java/com/example/wineycommon/aop/AopForTransaction.java
  Winey-Common/src/main/java/com/example/wineycommon/aop/RedissonCheckLockAop.java
  Winey-Common/src/main/java/com/example/wineycommon/config/AsyncConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/config/ConfigurationPropertiesConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/config/RedisConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/config/RedissonConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/properties/RedisProperties.java
  Winey-Common/src/main/resources/application-common.yml
  Winey-Domain/src/main/generated/com/example/wineydomain/badge/entity/QUserWineBadge.java
  Winey-Domain/src/main/generated/com/example/wineydomain/user/entity/QAuthority.java
  Winey-Domain/src/main/generated/com/example/wineydomain/user/entity/QUser.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/entity/Badge.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/entity/UserWineBadge.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/repository/UserWineBadgeRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/redis/entity/AccessToken.java
  Winey-Domain/src/main/java/com/example/wineydomain/redis/entity/RefreshToken.java
  Winey-Domain/src/main/java/com/example/wineydomain/redis/repository/AccessTokenRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/redis/repository/RefreshTokenRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/tastingNote/repository/TastingNoteRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/Authority.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/User.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/exception/UserErrorCode.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/repository/AuthorityRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/repository/UserRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/wine/repository/RecommendWineRepository.java
  Winey-Infrastructure/src/main/java/com/example/wineyinfrastructure/amazonS3/service/S3UploadService.java
  badge.md
  build.gradle
  winetip.md
Labels: 🚀Feature

#40 [Win 130] 와인 뱃지 추가 구현
  .github/workflows/dev_api_ci_cd.yml
  Winey-API/src/main/java/com/example/wineyapi/common/util/TimeUtils.java
  Winey-API/src/main/java/com/example/wineyapi/config/SecurityConfig.java
  Winey-API/src/main/java/com/example/wineyapi/tastingNote/convertor/TastingNoteConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/tastingNote/service/TastingNoteServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/user/controller/UserController.java
  Winey-API/src/main/java/com/example/wineyapi/user/converter/UserConnectionConverter.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserService.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeService.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeServiceImpl.java
  Winey-Common/src/main/java/com/example/wineycommon/config/AsyncConfig.java
  Winey-Domain/src/main/generated/com/example/wineydomain/user/entity/QUser.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/User.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/UserConnection.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/repository/UserConnectionRepository.java
Labels: 🚀Feature, 🔨Refactor
