Repository AdultOfNineteen/WINEY-Server, pull requests merged in 2024-01, with the labels that each got.

#62 WIN-166 : 와인 뱃지 상세조회 API
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/controller/WineBadgeController.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/convertor/WineBadgeConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/dto/WineBadgeResponse.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeService.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeServiceImpl.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/errorcode/CommonResponseStatus.java
  Winey-Domain/src/main/generated/com/example/wineydomain/badge/entity/QUserWineBadge.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/entity/UserWineBadge.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/exception/WineBadgeErrorCode.java
Labels: 🚀Feature

#68 fix: FCM 토큰 삭제 로직 추가 in 회원 탈퇴
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/repository/UserFcmTokenRepository.java
Labels: 🐛Bug

#66 와잇 뱃지 계산 로직 수정
  Winey-API/src/main/java/com/example/wineyapi/common/message/MessageConverter.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/convertor/WineBadgeConvertor.java
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeServiceImpl.java
  Winey-Common/src/main/java/com/example/wineycommon/config/RedisConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/constants/WineyStatic.java
  Winey-Domain/src/main/generated/com/example/wineydomain/badge/entity/QUserWineBadge.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/entity/UserWineBadge.java
  Winey-Domain/src/main/java/com/example/wineydomain/badge/repository/WineBadgeRepository.java
Labels: 🔨Refactor

#69 상점 관련 API 작성
  Winey-API/src/main/java/com/example/wineyapi/admin/shop/controller/AdminShopController.java
  Winey-API/src/main/java/com/example/wineyapi/admin/shop/converter/AdminShopConverter.java
  Winey-API/src/main/java/com/example/wineyapi/admin/shop/dto/ShopReq.java
  Winey-API/src/main/java/com/example/wineyapi/admin/shop/service/AdminShopService.java
  Winey-API/src/main/java/com/example/wineyapi/common/dto/Location.java
  Winey-API/src/main/java/com/example/wineyapi/common/util/GeoUtils.java
  Winey-API/src/main/java/com/example/wineyapi/shop/controller/ShopController.java
  Winey-API/src/main/java/com/example/wineyapi/shop/controller/ShopFilter.java
  Winey-API/src/main/java/com/example/wineyapi/shop/converter/ShopConverter.java
  Winey-API/src/main/java/com/example/wineyapi/shop/dto/ShopCommand.java
  Winey-API/src/main/java/com/example/wineyapi/shop/dto/ShopReq.java
  Winey-API/src/main/java/com/example/wineyapi/shop/dto/ShopRes.java
  Winey-API/src/main/java/com/example/wineyapi/shop/mapper/ShopMapper.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/ShopService.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/ShopServiceImpl.java
  Winey-Common/build.gradle
  Winey-Common/src/main/java/com/example/wineycommon/constants/WineyStatic.java
  Winey-Domain/build.gradle
  Winey-Domain/src/main/generated/com/example/wineydomain/shop/entity/QShop.java
  Winey-Domain/src/main/generated/com/example/wineydomain/shop/entity/QShopMood.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/BookMarkPk.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/Mood.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/Shop.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/ShopBookMark.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/ShopMood.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/ShopType.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/repository/ShopCustomRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/repository/ShopMoodRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/repository/ShopRepository.java
  Winey-Domain/src/main/resources/application-domain-dev.yml
  Winey-Domain/src/main/resources/application-domain-local-dev.yml
  Winey-Domain/src/main/resources/application-domain-local.yml
  Winey-Domain/src/main/resources/application-domain-prod.yml
  build.gradle
Labels: 🚀Feature

#71 500에러 슬랙 알림 구현
  .github/workflows/dev_api_ci_cd.yml
  Winey-API/src/main/java/com/example/wineyapi/wineBadge/service/WineBadgeServiceImpl.java
  Winey-Common/build.gradle
  Winey-Common/src/main/java/com/example/wineycommon/config/AsyncConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/config/SlackApiConfig.java
  Winey-Common/src/main/java/com/example/wineycommon/constants/SlackStatic.java
  Winey-Common/src/main/java/com/example/wineycommon/exception/ExceptionAdvice.java
  Winey-Common/src/main/java/com/example/wineycommon/service/SlackConverter.java
  Winey-Common/src/main/java/com/example/wineycommon/service/SlackService.java
  Winey-Common/src/main/resources/application-common.yml
  Winey-Domain/src/main/generated/com/example/wineydomain/user/entity/QUser.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/entity/User.java
  Winey-Domain/src/main/java/com/example/wineydomain/user/repository/UserConnectionRepository.java
Labels: 🚀Feature

#73 [#72] 상점 필터링 서비스 로직 코드 수정
  Winey-API/src/main/java/com/example/wineyapi/shop/dto/ShopReq.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/ShopServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/context/ShopListContext.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/context/ShopListContextFactory.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/strategy/AllShopListStrategy.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/strategy/FilterShopListStrategy.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/strategy/LikeShopListStrategy.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/strategy/ShopListStrategy.java
Labels: 🔨Refactor

#80 Feat: 이용약관 파일 추가
  Winey-API/src/main/java/com/example/wineyapi/config/SecurityConfig.java
  Winey-API/src/main/resources/static/docs/privacy-policy.html
  Winey-API/src/main/resources/static/docs/service-policy.html
Labels: 🚀Feature

#78 지도 북마크 기능 구현
  Winey-API/src/main/java/com/example/wineyapi/common/aop/LogAspect.java
  Winey-API/src/main/java/com/example/wineyapi/shop/controller/ShopController.java
  Winey-API/src/main/java/com/example/wineyapi/shop/converter/ShopConverter.java
  Winey-API/src/main/java/com/example/wineyapi/shop/dto/ShopRes.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/ShopService.java
  Winey-API/src/main/java/com/example/wineyapi/shop/service/ShopServiceImpl.java
  Winey-API/src/main/java/com/example/wineyapi/user/controller/UserController.java
  Winey-API/src/main/java/com/example/wineyapi/user/converter/UserConverter.java
  Winey-API/src/main/java/com/example/wineyapi/user/dto/UserResponse.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserService.java
  Winey-API/src/main/java/com/example/wineyapi/user/service/UserServiceImpl.java
  Winey-Common/src/main/java/com/example/wineycommon/constants/WineyStatic.java
  Winey-Domain/build.gradle
  Winey-Domain/src/main/java/com/example/wineydomain/shop/entity/Shop.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/exception/GetShopErrorCode.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/repository/ShopBookMarkRepository.java
  Winey-Domain/src/main/java/com/example/wineydomain/shop/repository/ShopRepository.java
Labels: 🚀Feature
